version: '3'

services:
  web:
    build: .
    environment:
      - FLASK_APP=insight
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
    volumes:
      - .:/app
    ports:
      - 5000:5000
    command: flask run -h 0.0.0.0 -p 5000
